#!/bin/zsh

# vm

# Generates Vagrantfile for the step specified by an integer argument.
# &/or deletes previously generated & copied files
# For usage run `./p2v`

# Vagrant Manager Application
source ./provision/vm/p2v_application.sh

# Check if there are no flags or arguments
# If none, display usage. Otherwise run script, starting with banner
if (( "$#" == 0 )); then
	cat "./provision/vm/txt/application_usage.txt"
	exit 0
fi

#p2v "$@"
